.PHONY : clean all fetch

all:
	m3dc1_mfmgen input

fetch:
	wget -O circle_0.1.txt 'https://drive.google.com/uc?export=download&id=1B_pnnn5VSvcol4IPbhbAEvNI_TLhy_0y'
	wget -O circle_0.1-9180.smb 'https://drive.google.com/uc?export=download&id=1iwvquDmbUUBMTdCuqy7VwA_w4IBHczE4'

clean:
	rm -fr *.smb *.txt *.sms *.smd *.vtk *.dmg *.log *~
