.PHONY : clean all fetch

all:
	m3dc1_mfmgen input

fetch:
	wget -O circle_0.02.txt 'https://drive.google.com/uc?export=download&id=1OxfiNXuXwQZuljPAIchkXU-eSTUT-DqH'
	wget -O circle_0.02-23K0.smb 'https://drive.google.com/uc?export=download&id=1hPpsuwbj1o2wZjfOIRw-JJpWUqGEK2Hx'

clean:
	rm -fr *.smb *.txt *.sms *.smd *.vtk *.dmg *.log *~
