.PHONY : clean all fetch

all:
	m3dc1_mfmgen input

fetch:
	wget -O circle_0.04.txt 'https://drive.google.com/uc?export=download&id=1MK6FiWdp2O4ULZyInPCXo-uU-PBNx9mV'
	wget -O circle_0.04-5K0.smb 'https://drive.google.com/uc?export=download&id=1jLuYpEqC05plopujI8ZgNvqqTn8MogrJ'

clean:
	rm -fr *.smb *.txt *.sms *.smd *.vtk *.dmg *.log *~
