.PHONY : clean

clean :
	find . -type f \
	-not -name 'C1input' \
	-not -name 'profile_ne' \
	-not -name 'profile_te' \
	-not -name 'profile_omega' \
	-not -name 'coil.dat' \
	-not -name 'current.dat' \
	-not -name 'rmp_coil.dat' \
	-not -name 'rmp_current.dat' \
	-not -name 'geqdsk' \
	-not -name 'diiid.txt' \
	-not -name 'mesh0.smb' \
	-not -name 'batchjob.*' \
	-not -name 'makefile' \
	-delete
